name: Build Raspberry Pi custom image

on: [push]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        with:
          image-name: test
          stage-list: stage0 stage1 stage2
