name: Build Raspberry Pi custom image

on: [push]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build-rpi-image
        with:
          image-name: rpi-image
          stage-list: stage0 stage1 stage2
          increase-runner-disk-size: true
          verbose-output: true
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-image
          path: ${{ steps.build-rpi-image.outputs.image-path }}
