name: Build Raspberry Pi custom image

on: [workflow_dispatch]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build-rpi-image
        with:
          hostname: ${{ vars.HOSTNAME }}
          image-name: rpi-image
          increase-runner-disk-size: true
          stage-list: stage0 stage1 stage2
          verbose-output: true
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-image
          path: ${{ steps.build-rpi-image.outputs.image-path }}
