name: Build Raspberry Pi custom image

on: [workflow_dispatch]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build-rpi-image
        with:
          disable-first-boot-user-rename: 1
          hostname: ${{ vars.HOSTNAME }}
          image-name: rpi-image
          increase-runner-disk-size: true
          keyboard-keymap: ${{ vars.KEYBOARD_KEYMAP }}
          keyboard-layout: ${{ vars.KEYBOARD_LAYOUT }}
          locale: ${{ vars.LOCALE }}
          password: ${{ secrets.PASSWORD }}
          stage-list: stage0 stage1 stage2
          timezone: ${{ vars.TIMEZONE }}
          username: ${{ vars.USERNAME }}
          verbose-output: true
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-image
          path: ${{ steps.build-rpi-image.outputs.image-path }}
