name: Build Raspberry Pi custom image

on: [workflow_dispatch]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build-rpi-image
        with:
          disable-first-boot-user-rename: 1
          hostname: ${{ secrets.HOSTNAME }}
          image-name: rpi-image
          increase-runner-disk-size: true
          keyboard-keymap: ${{ vars.KEYBOARD_KEYMAP }}
          keyboard-layout: ${{ vars.KEYBOARD_LAYOUT }}
          locale: ${{ vars.LOCALE }}
          password: ${{ secrets.PASSWORD }}
          pi-gen-version: ${{ vars.PI_GEN_VERSION }}
          pubkey-only-ssh: 1
          pubkey-ssh-first-user: ${{ secrets.PUBKEY_SSH_FIRST_USER }}
          stage-list: stage0 stage1 stage2
          timezone: ${{ vars.TIMEZONE }}
          username: ${{ secrets.USERNAME }}
          verbose-output: ${{ vars.VERBOSE_OUTPUT }}
          test-multiline-var: ${{ vars.MULTILINE_VAR }}
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-image
          path: ${{ steps.build-rpi-image.outputs.image-path }}
