name: Build Raspberry Pi custom image

on: [workflow_dispatch]
jobs:
  build-rpi-custom-image:
    runs-on: ubuntu-latest
    steps:
      - name: var test
        run: |
          echo "env... $MY_ENV_VAR"
          echo "var... $MY_CONF_VAR"
        env:
          MY_ENV_VAR: ${{ env.MY_ENV_VAR }}
          MY_CONF_VAR: ${{ vars.MY_CONF_VAR }}
      - uses: usimd/pi-gen-action@v1
        id: build-rpi-image
        with:
          image-name: rpi-image
          increase-runner-disk-size: true
          stage-list: stage0 stage1 stage2
          verbose-output: true
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-image
          path: ${{ steps.build-rpi-image.outputs.image-path }}
